language:
- objective-c

env:
  global:
    - secure: "OXWtO3ev0tveWquT4N2xnCIbBxJMh8pBrpfasU6393mEgOFS9IB81VcEfD8HIm8rt2lDHl5g8JPIPfByDQgY+VtoBeASr0O6po/UQluIPM2K3nm466mUAfz7mvi5hl3KDR7ohkaaFdW5DcRGJ8BrJpRsCLngaZnYOCbZcW/h/A8t9FcLWZo2h3Oex0UeBKKaxf5tGXEt4JjqHRcOsK/Jv9SmFEo6lavL6/quKRmUoZUBgzNIriME4/eUE1kDSE5re2jII5W9DNQO1L6YYTxMqgcXqdVw6uNZ1VQxeHARhVcjvzA2RHwPs/Sb+uEAWg7VM0YuR/pQI3Gh+5lmPm3+L1oBJS99z4Mit6xB/dTKfwoesXhrdG8mggVHvEvcUkLpHuYbkPPvNnHjXb9dzX/YpTp7N+gSAyBLy2PaVrSQxp2U4jOuYEf82jH+bWGn6AgDEiCvqMHkP81PDdYiwRjSdwlRNGN6TdX3wsCXT0YnG73wZftyY/xQxYsrcqfOhr16GXqBBBsNVKVsCV1/VsJkoQnnF8bCwqW3urMufj3emCMCDZlWTtC7RC4PQjdkUeJgA6MiZelrh6D50DFO9L0cjPMC++SIokItA76zYSn9CcVLq0Oxmh/GL6pwMktY/dg6j4nkh6WP82L+kBBxhGS0ZY0aXJdaPYoiYufrBZn1cSU="
    
matrix:
  include: 
  - python: 2.7
    env:
    - PYTHON_VERSION="2.7"

before_install:
  - brew update
  - brew install swig

install: source build_wheel.sh

script:
  - "whl_file=$(echo *.whl)"
    
after_success:
  - source deploy_wheel.sh

